### ISSUE TITLE
Immediately render image?

### ISSUE THREAD

**Issue by mharper6008** [ailon/markerjs-live#6]
Is there a way to immediately have markerLive render the combined source image with marker overlays, much like what you get from markerjs render event, instead of rendering the marker objects on top of the source image?  I'm looking for the best approach for zooming and scrolling since the markers don't automatically scale in realtime with the zoomed image.  For this use case, while editing, I don't store the resulting marked-up rendered image.  I keep the source image and markup separate for the ability to modify the markup over time.  But, for view only, need the ability to zoom and scroll.  Thoughts?

**Comment by ailon** [comment]
There's a method for that in marker.js
https://markerjs.com/reference/classes/markerarea.html#renderstate

Based on your description, I understand that you don't really use any features of marker.js Live, so I guess it would make sense to just use marker.js and that's it.
