### ISSUE TITLE
not able to zoom

### ISSUE THREAD

**Issue by eht22** [ailon/markerjs-live#7]
Hi is there any zooming function available in marker js live. If yes could you pls help me how to do that?

**Comment by ailon** [comment]
Hi. There's no built-in zooming function in marker.js Live.

**Comment by eht22** [comment]
is there any way to extend it's function make it possible?

**Comment by ailon** [comment]
You can just wrap it in an external div and control it through something like `style="transform:scale(2);"`

**Comment by eht22** [comment]
Yeah  it transform the div and image but not the marker

**Comment by ailon** [comment]
I made a quick demo [here](https://codesandbox.io/s/marker-js-live-zooming-pmxc47?file=/src/index.js)

Quick explanation: wrapped image in a `div` with `position: relative`. Set `targetRoot` on `MarkerView` to that `div`. Apply `scale()` transform to the div.

Seems to be working OK.

Hope this helps.
