### ISSUE TITLE
In Chrome, after clicking a marker, can't select any text on page

### ISSUE THREAD

**Issue by lluis** [ailon/markerjs-live#9]
Hi!
This can be tested here: https://markerjs.com/demos/markerjs-live/all-defaults
Open the demo page with Chrome, click on "can't have logos" yellow marker, then try to select any text in the page.
It only selects text by double-clicking
If you click in the image, in any place without a marker, select starts working again

**Comment by ailon** [comment]
Yes, I can see the issue. Thank you for reporting this! I'll take a look and fix it.

**Comment by ailon** [comment]
This should be fixed now in v1.2.1 (demo's haven't been updated yet).

**Comment by lluis** [comment]
Thanks! that was really fast
